# Site settings
title:       Life.
email:       thebathroompass@gmail.com
author:      Bathroom Pass
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     "/"
url:         "bathroompass.github.io/life"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username:
twitter_username:
google_plus_id:   112247890029620267118
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
